// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-E9dla6kGxp7zZjJbGbnObO_vOYAVoWY',
    appId: '1:428657444013:web:ddc185fd6a700d442d3224',
    messagingSenderId: '428657444013',
    projectId: 'flashcardsapp-3a3c0',
    authDomain: 'flashcardsapp-3a3c0.firebaseapp.com',
    storageBucket: 'flashcardsapp-3a3c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe6mslpq1LrIy4bU_Jx7-wgBBhI8rJezI',
    appId: '1:428657444013:android:69f37ea3e15cadcf2d3224',
    messagingSenderId: '428657444013',
    projectId: 'flashcardsapp-3a3c0',
    storageBucket: 'flashcardsapp-3a3c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ52RF3wdnVYiin0GNy0Pm4E8HLmbll1g',
    appId: '1:428657444013:ios:265068fba4df253d2d3224',
    messagingSenderId: '428657444013',
    projectId: 'flashcardsapp-3a3c0',
    storageBucket: 'flashcardsapp-3a3c0.appspot.com',
    iosBundleId: 'com.example.flashCardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ52RF3wdnVYiin0GNy0Pm4E8HLmbll1g',
    appId: '1:428657444013:ios:4ded7784288887d02d3224',
    messagingSenderId: '428657444013',
    projectId: 'flashcardsapp-3a3c0',
    storageBucket: 'flashcardsapp-3a3c0.appspot.com',
    iosBundleId: 'com.example.flashCardApp.RunnerTests',
  );
}
